spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/movie"
    username: "postgres"
    password: "admin"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
        format_sql: true
  application:
    name: movie

server:
  port: 9092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka